### PR TITLE
Trying to make examples run on containers easily

### PR DESCRIPTION
**Pull request by hibariya**
Hello. I have been playing with the example codes since I was curious if I could run all the examples in Docker containers. As a result, I could have confirmed that most of the examples run on containers.

I think it's great if developers could try the examples out of the box with Docker. Because it will not require them to set up the development environment to try an example. So I opened this PR. 

However, there are some concerns. It adds a certain amount of files and it might increase the maintenance cost of this repository. I'd like to discuss this to make it better if you don't mind. I'd appreciate your advice.

Maybe we can make sure that all the app container boot without errors on CI (GitHub Actions?) to keep these files healthy to a certain extent.

It's OK to close this PR since it's just a kind of side effect of my investigation out of my curiosity. But if you find it's worth to do it, I will willingly work on it.

## Maintaining the docker-compose.yml files

I found that most part of the docker-compose.yml can be shared between the examples. So I put the original YAML files under the `docker-compose/` directory. I also created Rake tasks that copy the files for each example.

In this way, we can edit the original YAML files and copy them to example apps.

```
$ $EDITOR docker-compose/ruby.yml
$ rake docker-compose
cp docker-compose/dotnet.yml fixed-price-subscriptions/server/dotnet/docker-compose.yml
cp docker-compose/go.yml fixed-price-subscriptions/server/go/docker-compose.yml
cp docker-compose/java.yml fixed-price-subscriptions/server/java/docker-compose.yml
...
```

## Apps I cannot confirm so far

There is a couple of apps I couldn't confirm due to the following errors.

###  `per-seat-subscriptions/server/dotnet/`

Failed to proceed due to incompatible API version of events (2020-08-27 vs. 2020-03-02). When I updated Stripe.net, I got another error because of the library API changes.

### `per-seat-subscriptions/server/node/`

The web server booted but I got an error `No signatures found matching the expected signature for payload.` when I registered an email address. I have no idea why this happens.

## Other concerns

* English is not my first language, so feel free to point out errors and unnatural expressions.

### CODE REVIEW

**Comment by cjavilla-stripe** [comment]
Wow this is awesome @hibariya. We'll have the team take a look and share some thoughts!

**Comment by cjavilla-stripe** [comment]
Thanks again so much for your contributions, @hibariya! I'd love to learn a bit more about how this works before merging. We're a small team and if we went down this path, I want to make sure we fully grasp how the docker components fit together and how we can leverage them. 

I also want to make sure that we're keeping the amount of code to a minimum so that it's easy for developers to find what is relevant to their integration. One worry I have is this might confuse some folks who might think that docker is required. 

It's a really cool concept and I think it could help us with testing for samples. Would love to chat more and connect with you if you're open to that.

**Comment by hibariya** [comment]
@cjavilla-stripe Thank you for considering that! I understand. Yes, I'd love to discuss the details with any communication tool that most convenient for you, such as Zoom, Meet, and/or IRC.

> I also want to make sure that we're keeping the amount of code to a minimum so that it's easy for developers to find what is relevant to their integration. One worry I have is this might confuse some folks who might think that docker is required.

Sure. Currently, I have checked in the copies of them for each server implementation using the rake tasks. I think it might a little be redundant and cause distractions. From this point of view, as another option, I think we can just provide the YAML files on top of this repository and only provide instructions to use Docker in each README file.

**Comment by cjavilla-stripe** [comment]
@hibariya would love to setup a time to zoom. Can you email me cjavilla at stripe.com and I'll set something up?

**Comment by cjavilla-stripe** [comment]
@hibariya and I are working on another solution in stripe-samples/sample-ci

**Pull request closed without merging**
